apiVersion: v1
kind: Service
metadata:
  labels:
    app: podinfo
  name: podinfo
spec:
  ports:
  - port: 9898
    name: http
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
  type: ClusterIP
