# permissions for end users to view localratelimitconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localratelimitconfig-viewer-role
rules:
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - localratelimitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - localratelimitconfigs/status
  verbs:
  - get
