# permissions for end users to edit ratelimitservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ratelimitservice-editor-role
rules:
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - ratelimitservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - ratelimitservices/status
  verbs:
  - get
