apiVersion: ratelimit.zufardhiyaulhaq.com/v1alpha1
kind: GlobalRateLimitConfig
metadata:
  name: podinfo
  namespace: development
spec:
  type: "sidecar"
  selector:
    labels:
      app: podinfo
    istio_version:
      - "1.24"
      - "1.25"
      - "1.26"
  ratelimit:
    spec:
      domain: "podinfo"
      failure_mode_deny: false
      timeout: "10s"
      service:
        type: "service"
        name: "podinfo-ratelimit-service"
