apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "istio-ratelimit-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    manager: {{ .Release.Service }}
  name: {{ .Release.Name }}-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
