apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-settings
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "istio-ratelimit-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    manager: {{ .Release.Service }}
data:
  RATE_LIMIT_SERVICE_IMAGE: {{ .Values.settings.ratelimitservice.image }}
