apiVersion: ratelimit.zufardhiyaulhaq.com/v1alpha1
kind: GlobalRateLimitConfig
metadata:
  name: ingressgateway
  namespace: istio-system
spec:
  type: "gateway"
  selector:
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
    istio_version:
      - "1.14"
      - "1.15"
      - "1.16"
      - "1.17"
  ratelimit:
    spec:
      domain: "ingressgateway"
      failure_mode_deny: false
      timeout: "10s"
      service:
        type: "service"
        name: "ingressgateway-ratelimit-service"
