// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimit) DeepCopyInto(out *GlobalRateLimit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimit.
func (in *GlobalRateLimit) DeepCopy() *GlobalRateLimit {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalRateLimit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfig) DeepCopyInto(out *GlobalRateLimitConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfig.
func (in *GlobalRateLimitConfig) DeepCopy() *GlobalRateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalRateLimitConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfigList) DeepCopyInto(out *GlobalRateLimitConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalRateLimitConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfigList.
func (in *GlobalRateLimitConfigList) DeepCopy() *GlobalRateLimitConfigList {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalRateLimitConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfigRatelimit) DeepCopyInto(out *GlobalRateLimitConfigRatelimit) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfigRatelimit.
func (in *GlobalRateLimitConfigRatelimit) DeepCopy() *GlobalRateLimitConfigRatelimit {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfigRatelimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfigRatelimitSpec) DeepCopyInto(out *GlobalRateLimitConfigRatelimitSpec) {
	*out = *in
	out.Service = in.Service
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfigRatelimitSpec.
func (in *GlobalRateLimitConfigRatelimitSpec) DeepCopy() *GlobalRateLimitConfigRatelimitSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfigRatelimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfigRatelimitSpecService) DeepCopyInto(out *GlobalRateLimitConfigRatelimitSpecService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfigRatelimitSpecService.
func (in *GlobalRateLimitConfigRatelimitSpecService) DeepCopy() *GlobalRateLimitConfigRatelimitSpecService {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfigRatelimitSpecService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfigSelector) DeepCopyInto(out *GlobalRateLimitConfigSelector) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IstioVersion != nil {
		in, out := &in.IstioVersion, &out.IstioVersion
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SNI != nil {
		in, out := &in.SNI, &out.SNI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfigSelector.
func (in *GlobalRateLimitConfigSelector) DeepCopy() *GlobalRateLimitConfigSelector {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfigSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfigSpec) DeepCopyInto(out *GlobalRateLimitConfigSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	out.Ratelimit = in.Ratelimit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfigSpec.
func (in *GlobalRateLimitConfigSpec) DeepCopy() *GlobalRateLimitConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfigStatus) DeepCopyInto(out *GlobalRateLimitConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfigStatus.
func (in *GlobalRateLimitConfigStatus) DeepCopy() *GlobalRateLimitConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitList) DeepCopyInto(out *GlobalRateLimitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalRateLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitList.
func (in *GlobalRateLimitList) DeepCopy() *GlobalRateLimitList {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalRateLimitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitSelector) DeepCopyInto(out *GlobalRateLimitSelector) {
	*out = *in
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitSelector.
func (in *GlobalRateLimitSelector) DeepCopy() *GlobalRateLimitSelector {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitSpec) DeepCopyInto(out *GlobalRateLimitSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = make([]*RateLimit_Action, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RateLimit_Action)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitSpec.
func (in *GlobalRateLimitSpec) DeepCopy() *GlobalRateLimitSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitStatus) DeepCopyInto(out *GlobalRateLimitStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitStatus.
func (in *GlobalRateLimitStatus) DeepCopy() *GlobalRateLimitStatus {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action) DeepCopyInto(out *RateLimit_Action) {
	*out = *in
	if in.SourceCluster != nil {
		in, out := &in.SourceCluster, &out.SourceCluster
		*out = new(RateLimit_Action_SourceCluster)
		**out = **in
	}
	if in.DestinationCluster != nil {
		in, out := &in.DestinationCluster, &out.DestinationCluster
		*out = new(RateLimit_Action_DestinationCluster)
		**out = **in
	}
	if in.RequestHeaders != nil {
		in, out := &in.RequestHeaders, &out.RequestHeaders
		*out = new(RateLimit_Action_RequestHeaders)
		**out = **in
	}
	if in.RemoteAddress != nil {
		in, out := &in.RemoteAddress, &out.RemoteAddress
		*out = new(RateLimit_Action_RemoteAddress)
		**out = **in
	}
	if in.GenericKey != nil {
		in, out := &in.GenericKey, &out.GenericKey
		*out = new(RateLimit_Action_GenericKey)
		**out = **in
	}
	if in.HeaderValueMatch != nil {
		in, out := &in.HeaderValueMatch, &out.HeaderValueMatch
		*out = new(RateLimit_Action_HeaderValueMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action.
func (in *RateLimit_Action) DeepCopy() *RateLimit_Action {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_DestinationCluster) DeepCopyInto(out *RateLimit_Action_DestinationCluster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_DestinationCluster.
func (in *RateLimit_Action_DestinationCluster) DeepCopy() *RateLimit_Action_DestinationCluster {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_DestinationCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_GenericKey) DeepCopyInto(out *RateLimit_Action_GenericKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_GenericKey.
func (in *RateLimit_Action_GenericKey) DeepCopy() *RateLimit_Action_GenericKey {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_GenericKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_HeaderValueMatch) DeepCopyInto(out *RateLimit_Action_HeaderValueMatch) {
	*out = *in
	if in.ExpectMatch != nil {
		in, out := &in.ExpectMatch, &out.ExpectMatch
		*out = new(bool)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]*RateLimit_Action_HeaderValueMatch_HeaderMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(RateLimit_Action_HeaderValueMatch_HeaderMatcher)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_HeaderValueMatch.
func (in *RateLimit_Action_HeaderValueMatch) DeepCopy() *RateLimit_Action_HeaderValueMatch {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_HeaderValueMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_HeaderValueMatch_HeaderMatcher) DeepCopyInto(out *RateLimit_Action_HeaderValueMatch_HeaderMatcher) {
	*out = *in
	if in.SafeRegexMatch != nil {
		in, out := &in.SafeRegexMatch, &out.SafeRegexMatch
		*out = new(RateLimit_Action_HeaderValueMatch_HeaderMatcher_RegexMatcher)
		**out = **in
	}
	if in.RangeMatch != nil {
		in, out := &in.RangeMatch, &out.RangeMatch
		*out = new(RateLimit_Action_HeaderValueMatch_HeaderMatcher_Int64Range)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_HeaderValueMatch_HeaderMatcher.
func (in *RateLimit_Action_HeaderValueMatch_HeaderMatcher) DeepCopy() *RateLimit_Action_HeaderValueMatch_HeaderMatcher {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_HeaderValueMatch_HeaderMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_HeaderValueMatch_HeaderMatcher_Int64Range) DeepCopyInto(out *RateLimit_Action_HeaderValueMatch_HeaderMatcher_Int64Range) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_HeaderValueMatch_HeaderMatcher_Int64Range.
func (in *RateLimit_Action_HeaderValueMatch_HeaderMatcher_Int64Range) DeepCopy() *RateLimit_Action_HeaderValueMatch_HeaderMatcher_Int64Range {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_HeaderValueMatch_HeaderMatcher_Int64Range)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_HeaderValueMatch_HeaderMatcher_RegexMatcher) DeepCopyInto(out *RateLimit_Action_HeaderValueMatch_HeaderMatcher_RegexMatcher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_HeaderValueMatch_HeaderMatcher_RegexMatcher.
func (in *RateLimit_Action_HeaderValueMatch_HeaderMatcher_RegexMatcher) DeepCopy() *RateLimit_Action_HeaderValueMatch_HeaderMatcher_RegexMatcher {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_HeaderValueMatch_HeaderMatcher_RegexMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_RemoteAddress) DeepCopyInto(out *RateLimit_Action_RemoteAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_RemoteAddress.
func (in *RateLimit_Action_RemoteAddress) DeepCopy() *RateLimit_Action_RemoteAddress {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_RemoteAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_RequestHeaders) DeepCopyInto(out *RateLimit_Action_RequestHeaders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_RequestHeaders.
func (in *RateLimit_Action_RequestHeaders) DeepCopy() *RateLimit_Action_RequestHeaders {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_RequestHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit_Action_SourceCluster) DeepCopyInto(out *RateLimit_Action_SourceCluster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit_Action_SourceCluster.
func (in *RateLimit_Action_SourceCluster) DeepCopy() *RateLimit_Action_SourceCluster {
	if in == nil {
		return nil
	}
	out := new(RateLimit_Action_SourceCluster)
	in.DeepCopyInto(out)
	return out
}
